export const surpriseOptions = [
  'A Beautiful Sunset over a forest fire',
  'A thing from your nightmares',
  'the inevitable end of an era',
  'the feeling of doom before a rainy day',
  'terrible cramps in your kneecaps',
  'the feeling of being watched',
  'constant and persistant constipation',
  'the woes of womanhood',
  'chasing the dragon',
  'Goliath beats David',
  'Darkness envelops the land, foretelling an age of despair.',
  'The sky weeps blood, a harbinger of impending catastrophe.',
  'Whispers of doom echo through the desolate halls of fate.',
  'The ground trembles beneath our feet, announcing an imminent disaster.',
  'Shadows crawl, heralding the arrival of an ancient malevolence.',
  'The veil between worlds thins, beckoning forth the horrors that lie beyond.',
  'A chilling silence settles, as if the world holds its breath before the storm.',
  "Mankind's final hour draws near, as the doomsday clock ticks relentlessly.",
  'Ominous clouds gather, portending an unforgiving tempest of destruction.',
  'A haunting prophecy looms, casting a pall of doom over all who hear its words.',
];
